version: "2"
linters:
  default: none
  enable:
    - gosec
  settings:
    gosec:
      excludes:
        - G104  # Errors unhandled (2 findings)
        - G117  # Invalid use of os.TempDir (1 finding)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
