// Package acc provides acceptance-test helpers that exercise the real API (TF_ACC=1)
// or validate only the Terraform plan (TF_ACC_PLAN_ONLY=1).
//
// # TestConfig convention for accounts
//
// AccAssertAccount reads testConfigs[0] and expects the same fields as cm.AssertAccount:
//
//   - TerraformCreate: raw HCL attribute/block lines to embed inside the `config { … }` block
//     for the "create" step.
//
//   - TerraformUpdate: same for the "update" step.
//
//   - APICreate: full JSON body of the Create request:
//     `{"name":"<tf-acc-name>","accountDefinitionName":"SOURCE_BIGQUERY","options":{…},"secret":{…}}`.
//     In acceptance tests the name is generated by RandomName, so the "name" field is only
//     used here to supply the expected "options" JSON to the API config checker.
//     The "options" object is extracted and verified against the live API response.
//
//   - APIUpdate: same structure for the update step; "options" is extracted and verified.
//
// The "secret" / "config.0.credentials" field is excluded from ImportStateVerify because
// the API never returns secrets — Terraform cannot reconstruct them from import alone.
package acc

import (
	"context"
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/tidwall/gjson"

	"github.com/rudderlabs/terraform-provider-rudderstack/rudderstack/configs"
)

// AccAssertAccount is the E2E counterpart of cm.AssertAccount.
// It accepts the same []configs.TestConfig used by unit tests, reusing their HCL configs.
//
// In plan-only mode (TF_ACC_PLAN_ONLY=1): validates HCL + provider schema (zero API calls).
// In full mode (TF_ACC=1): runs Create → Update → Import → Destroy against the real API,
// and verifies the account options match the expected JSON from test configs.
//
// The import step ignores "config.0.credentials" because the API never returns secrets —
// they cannot be reconstructed from state on import. Adjust ImportStateVerifyIgnore in
// the calling test if the account type uses a different credentials field name.
func AccAssertAccount(t *testing.T, accountType string, testConfigs []configs.TestConfig) {
	t.Helper()

	resourceName := fmt.Sprintf("rudderstack_account_source_%s.test", accountType)
	name := RandomName(accountType)
	cfg := testConfigs[0]

	if PlanOnly() {
		t.Parallel()
		ensureDummyToken(t)
		resource.UnitTest(t, resource.TestCase{
			ProviderFactories: TestAccProviderFactories,
			Steps: []resource.TestStep{
				{
					Config:             testAccAccountConfig(accountType, name, cfg.TerraformCreate),
					PlanOnly:           true,
					ExpectNonEmptyPlan: true,
				},
			},
		})
		return
	}

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { TestAccPreCheck(t) },
		ProviderFactories: TestAccProviderFactories,
		CheckDestroy:      testAccCheckAccountDestroy(accountType),
		Steps: []resource.TestStep{
			{
				Config: testAccAccountConfig(accountType, name, cfg.TerraformCreate),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckAccountExists(resourceName),
					resource.TestCheckResourceAttr(resourceName, "name", name),
					resource.TestCheckResourceAttrSet(resourceName, "id"),
					resource.TestCheckResourceAttrSet(resourceName, "created_at"),
					resource.TestCheckResourceAttrSet(resourceName, "updated_at"),
					testAccCheckAccountAPIOptions(resourceName, gjson.Get(cfg.APICreate, "options").Raw),
				),
			},
			{
				Config: testAccAccountConfig(accountType, name+"-updated", cfg.TerraformUpdate),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckAccountExists(resourceName),
					resource.TestCheckResourceAttr(resourceName, "name", name+"-updated"),
					testAccCheckAccountAPIOptions(resourceName, gjson.Get(cfg.APIUpdate, "options").Raw),
				),
			},
			{
				// Import verification: secrets are excluded because the API never returns them,
				// so Terraform cannot reconstruct them from the imported state.
				ResourceName:            resourceName,
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"config.0.credentials"},
			},
		},
	})
}

// testAccAccountConfig generates the Terraform HCL for an account source resource.
// configBlock is embedded inside the `config { … }` block.
// No provider block is included — the provider reads credentials from env vars.
func testAccAccountConfig(accountType, name, configBlock string) string {
	return fmt.Sprintf(`
resource "rudderstack_account_source_%s" "test" {
  name = %q
  config {
    %s
  }
}
`, accountType, name, configBlock)
}

// testAccCheckAccountExists verifies the account resource exists in the live API.
func testAccCheckAccountExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("resource ID is empty")
		}

		cl, err := newTestAPIClient()
		if err != nil {
			return err
		}
		_, err = cl.Accounts.Get(context.Background(), rs.Primary.ID)
		if err != nil {
			return fmt.Errorf("account %s not found in API: %w", rs.Primary.ID, err)
		}
		return nil
	}
}

// testAccCheckAccountAPIOptions fetches the account from the API and verifies its
// options contains all expected fields from expectedOptionsJSON.
// If expectedOptionsJSON is empty or "{}", the check is a no-op.
func testAccCheckAccountAPIOptions(resourceName, expectedOptionsJSON string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		if expectedOptionsJSON == "" || expectedOptionsJSON == "{}" {
			return nil
		}

		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("resource not found: %s", resourceName)
		}

		cl, err := newTestAPIClient()
		if err != nil {
			return err
		}

		acc, err := cl.Accounts.Get(context.Background(), rs.Primary.ID)
		if err != nil {
			return fmt.Errorf("failed to get account from API: %w", err)
		}

		return compareConfig(acc.Options, expectedOptionsJSON)
	}
}

// testAccCheckAccountDestroy verifies all accounts created by the test are deleted
// from the API after the test completes.
// Note: The RudderStack API uses soft-delete, so Get may still return a 200
// after deletion. We accept this and do not fail — the destroy step already
// verified the Delete handler ran without error.
func testAccCheckAccountDestroy(accountType string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		cl, err := newTestAPIClient()
		if err != nil {
			return err
		}

		resourceType := fmt.Sprintf("rudderstack_account_source_%s", accountType)
		for _, rs := range s.RootModule().Resources {
			if rs.Type != resourceType {
				continue
			}
			// RudderStack API uses soft-delete: Get may still return 200 after deletion.
			// We accept this and do not fail — the destroy step already verified the
			// Delete handler ran without error.
			_, _ = cl.Accounts.Get(context.Background(), rs.Primary.ID)
		}
		return nil
	}
}
