package generator

import (
	"encoding/json"
	"fmt"
	"log"
	"math"
	"os"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/zclconf/go-cty/cty"

	"github.com/rudderlabs/rudder-iac/api/client"
	"github.com/rudderlabs/rudder-iac/api/client/retl"
	"github.com/rudderlabs/terraform-provider-rudderstack/rudderstack/configs"
	_ "github.com/rudderlabs/terraform-provider-rudderstack/rudderstack/integrations"
)

var logger = log.New(os.Stderr, "", 0)

type sourceEntry struct {
	terraformType string
	source        client.Source
}

type destinationEntry struct {
	terraformType string
	destination   client.Destination
}

type retlSourceEntry struct {
	terraformType string
	source        retl.RETLSource
}

// GenerateImportScript generates terraform import commands that import resources from terraform script as generated by GenerateTerraform.
func GenerateImportScript(
	sources []client.Source,
	destinations []client.Destination,
	connections []client.Connection,
	retlSources []retl.RETLSource,
	retlConnections []retl.RETLConnection,
) ([]byte, error) {
	lines := []string{}

	sourceConfigs := configs.Sources.Entries()
	destinationConfigs := configs.Destinations.Entries()

	foundSources := map[string]bool{}
	foundDestinations := map[string]bool{}
	destinationTerraformTypes := map[string]string{} // destination ID -> terraform type
	foundRetlSources := map[string]bool{}

	for _, src := range sources {
		t, cm := configMeta(sourceConfigs, src.Type)
		if cm != nil {
			foundSources[src.ID] = true
			lines = append(lines, fmt.Sprintf(`terraform import "rudderstack_source_%s.%s" "%s"`, t, sourceName(src), src.ID))
		}
	}

	for _, dst := range destinations {
		t, cm := configMeta(destinationConfigs, dst.Type)
		if cm != nil {
			foundDestinations[dst.ID] = true
			destinationTerraformTypes[dst.ID] = t
			lines = append(lines, fmt.Sprintf(`terraform import "rudderstack_destination_%s.%s" "%s"`, t, destinationName(dst), dst.ID))
		}
	}

	for _, cnxn := range connections {
		_, oks := foundSources[cnxn.SourceID]
		_, okd := foundDestinations[cnxn.DestinationID]
		if oks && okd {
			lines = append(lines, fmt.Sprintf(`terraform import "rudderstack_connection.%s" "%s"`, connectionName(cnxn), cnxn.ID))
		}
	}

	for _, src := range retlSources {
		tType, reason, ok := retlSourceTerraformType(src)
		if !ok {
			logger.Printf("skipping RETL source '%s': %s", src.ID, reason)
			continue
		}
		foundRetlSources[src.ID] = true
		lines = append(lines, fmt.Sprintf(`terraform import "%s.%s" "%s"`, tType, retlSourceName(src), src.ID))
	}

	for _, cnxn := range retlConnections {
		if !foundRetlSources[cnxn.SourceID] {
			continue
		}
		if !foundDestinations[cnxn.DestinationID] {
			continue
		}
		// Skip unsupported destination-specific flows — these are skipped in
		// the HCL generator too, so we mustn't emit an import line for a
		// resource that doesn't exist.
		if len(cnxn.DestinationConfig) > 0 && destinationTerraformTypes[cnxn.DestinationID] != "customerio_audience" {
			continue
		}
		// For customerio_audience, mirror the HCL generator's hard-skip when
		// the typed block can't be decoded.
		if destinationTerraformTypes[cnxn.DestinationID] == "customerio_audience" && len(cnxn.DestinationConfig) > 0 {
			if _, err := customerIOAudienceConfigBlock(cnxn.DestinationConfig); err != nil {
				continue
			}
		}
		lines = append(lines, fmt.Sprintf(`terraform import "rudderstack_retl_connection.%s" "%s"`, retlConnectionName(cnxn), cnxn.ID))
	}

	script := strings.Join(lines, "\n")
	return []byte(script), nil
}

// Generate HCL script from a given set of API sources, destinations and connections.
func GenerateTerraform(
	sources []client.Source,
	destinations []client.Destination,
	connections []client.Connection,
	retlSources []retl.RETLSource,
	retlConnections []retl.RETLConnection,
) ([]byte, error) {
	f := hclwrite.NewEmptyFile()
	body := f.Body()

	// generate source blocks for supported sources
	sourceConfigs := configs.Sources.Entries()
	generatedSourceEntries := map[string]*sourceEntry{}
	for _, src := range sources {
		terraformType, cm := configMeta(sourceConfigs, src.Type)
		if cm != nil {
			b, err := generateSource(src, terraformType, cm)
			if err != nil {
				logger.Printf("could not generate resource block for source '%s': %v", src.ID, err)
			} else {
				body.AppendBlock(b)
				body.AppendNewline()
				generatedSourceEntries[src.ID] = &sourceEntry{terraformType: terraformType, source: src}
			}
		} else {
			logger.Printf("could not generate resource block for source '%s': type '%s' is not supported", src.ID, src.Type)
		}
	}

	// generate destination blocks for supported destinations
	destinationConfigs := configs.Destinations.Entries()
	generatedDestinationEntries := map[string]*destinationEntry{}
	for _, dst := range destinations {
		terraformType, cm := configMeta(destinationConfigs, dst.Type)
		if cm != nil {
			b, err := generateDestination(dst, terraformType, cm)
			if err != nil {
				logger.Printf("could not generate resource block for destination '%s': %v", dst.ID, err)
			} else {
				body.AppendBlock(b)
				body.AppendNewline()
				generatedDestinationEntries[dst.ID] = &destinationEntry{terraformType: terraformType, destination: dst}
			}
		} else {
			logger.Printf("could not generate resource block for destination '%s': type '%s' is not supported", dst.ID, dst.Type)
		}
	}

	// generate connection blocks for supported sources and destinations
	for _, cnxn := range connections {
		src, oks := generatedSourceEntries[cnxn.SourceID]
		dst, okd := generatedDestinationEntries[cnxn.DestinationID]
		if !oks {
			logger.Printf("could not generate resource block for connection '%s': connected source '%s' is not supported", cnxn.ID, cnxn.SourceID)
		} else if !okd {
			logger.Printf("could not generate resource block for connection '%s': connected destination '%s' is not supported", cnxn.ID, cnxn.DestinationID)
		} else {
			b, err := generateConnection(cnxn, src, dst)
			if err != nil {
				return nil, fmt.Errorf("could not generate resource block for connection '%s': %w", cnxn.ID, err)
			}

			body.AppendBlock(b)
			body.AppendNewline()
		}
	}

	// generate RETL source blocks for supported types (model + non-s3 table)
	generatedRetlSources := map[string]*retlSourceEntry{}
	for _, src := range retlSources {
		tType, reason, ok := retlSourceTerraformType(src)
		if !ok {
			logger.Printf("could not generate resource block for RETL source '%s': %s", src.ID, reason)
			continue
		}
		b, err := generateRetlSource(src, tType)
		if err != nil {
			logger.Printf("could not generate resource block for RETL source '%s': %v", src.ID, err)
			continue
		}
		body.AppendBlock(b)
		body.AppendNewline()
		generatedRetlSources[src.ID] = &retlSourceEntry{terraformType: tType, source: src}
	}

	// generate RETL connection blocks (only when both source and destination were generated)
	for _, cnxn := range retlConnections {
		src, oks := generatedRetlSources[cnxn.SourceID]
		dst, okd := generatedDestinationEntries[cnxn.DestinationID]
		if !oks {
			logger.Printf("could not generate resource block for RETL connection '%s': RETL source '%s' is not supported", cnxn.ID, cnxn.SourceID)
			continue
		}
		if !okd {
			logger.Printf("could not generate resource block for RETL connection '%s': destination '%s' is not supported", cnxn.ID, cnxn.DestinationID)
			continue
		}
		// Customer.io Audience is the only destination-specific flow this
		// resource exposes as a typed block. Any other destination with a
		// non-empty destinationConfig is a VDM-next flow we don't support —
		// skip rather than emit a connection we can't represent.
		if len(cnxn.DestinationConfig) > 0 && dst.terraformType != "customerio_audience" {
			logger.Printf("skipping RETL connection '%s': destination-specific flow for '%s' is not supported", cnxn.ID, dst.terraformType)
			continue
		}
		// For customerio_audience, the typed block is mandatory: emitting the
		// connection without it would produce HCL that can't roundtrip on
		// import. Skip the whole connection if decoding fails.
		if dst.terraformType == "customerio_audience" && len(cnxn.DestinationConfig) > 0 {
			if _, err := customerIOAudienceConfigBlock(cnxn.DestinationConfig); err != nil {
				logger.Printf("skipping RETL connection '%s': cannot decode customerio_audience destinationConfig (%v)", cnxn.ID, err)
				continue
			}
		}
		b, err := generateRetlConnection(cnxn, src, dst)
		if err != nil {
			// generateRetlConnection only returns an error from its panic
			// recovery (defensive against an unforeseen hclwrite bug). If we
			// ever hit it the file is half-built — fail fast rather than
			// emit corrupt HCL.
			return nil, fmt.Errorf("could not generate resource block for RETL connection '%s': %w", cnxn.ID, err)
		}
		body.AppendBlock(b)
		body.AppendNewline()
	}

	return f.Bytes(), nil
}

// generateSource generates a source resource block from an API source object and a terraform source type and ConfigMeta.
func generateSource(source client.Source, terraformType string, cm *configs.ConfigMeta) (block *hclwrite.Block, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic while generating source block: %v", r)
		}
	}()

	resourceType := sourceType(terraformType)
	resourceName := sourceName(source)
	block = hclwrite.NewBlock("resource", []string{resourceType, resourceName})

	body := block.Body()
	body.SetAttributeValue("name", cty.StringVal(source.Name))

	if !cm.SkipConfig {
		configBlock, err := generateConfigBlock(source.Config, cm)
		if err != nil {
			return nil, fmt.Errorf("could not generate config block for source '%s': %w", source.ID, err)
		}
		body.AppendBlock(configBlock)
	}

	if cm.SettingsSchema != nil && (source.GeoEnrichmentEnabled != nil || source.Transient != nil) {
		settingsBlock, err := generateSettingsBlock(source, cm)
		if err != nil {
			return nil, fmt.Errorf("could not generate settings block for source '%s': %w", source.ID, err)
		}
		if settingsBlock != nil {
			body.AppendBlock(settingsBlock)
		}
	}

	return block, nil
}

// generateSettingsBlock generates a settings block from source-level settings fields.
func generateSettingsBlock(source client.Source, cm *configs.ConfigMeta) (*hclwrite.Block, error) {
	settingsAPIMap := map[string]interface{}{}
	if source.GeoEnrichmentEnabled != nil {
		settingsAPIMap["geoEnrichmentEnabled"] = *source.GeoEnrichmentEnabled
	}
	if source.Transient != nil {
		settingsAPIMap["transient"] = *source.Transient
	}

	settingsAPIJSON, err := json.Marshal(settingsAPIMap)
	if err != nil {
		return nil, fmt.Errorf("could not marshal settings: %w", err)
	}

	settingsState, err := cm.SettingsAPIToState(string(settingsAPIJSON))
	if err != nil {
		return nil, fmt.Errorf("could not convert settings API to state: %w", err)
	}

	var stateMap map[string]interface{}
	if err := json.Unmarshal([]byte(settingsState), &stateMap); err != nil {
		return nil, err
	}

	if len(stateMap) == 0 {
		return nil, nil
	}

	return generateBlock("settings", stateMap, cm.SettingsSchema)
}

func sourceType(terraformType string) string {
	return fmt.Sprintf("rudderstack_source_%s", terraformType)
}

func sourceName(source client.Source) string {
	return fmt.Sprintf("src_%s", source.ID)
}

func cleanupDestinationConfig(destination client.Destination) client.Destination {
	var jsonConfig map[string]any
	err := json.Unmarshal(destination.Config, &jsonConfig)
	if err != nil {
		logger.Printf("could not unmarshal destination config: %v", err)
		return destination
	}

	jsonConfig = cleanupEventFilteringConfig(jsonConfig)
	jsonConfig = cleanupConsentManagementConfig(jsonConfig)

	jsonConfigBytes, err := json.Marshal(jsonConfig)
	if err != nil {
		logger.Printf("could not marshal destination config: %v", err)
	}
	destination.Config = json.RawMessage(jsonConfigBytes)
	return destination
}

func cleanupEventFilteringConfig(jsonConfig map[string]any) map[string]any {
	// Ensure blacklistedEvents and whitelistedEvents are defined only as per the value of eventFilteringOption
	eventFilteringOption, ok := jsonConfig["eventFilteringOption"]
	if !ok || eventFilteringOption == "disable" || eventFilteringOption == nil {
		delete(jsonConfig, "blacklistedEvents")
		delete(jsonConfig, "whitelistedEvents")
		delete(jsonConfig, "eventFilteringOption")
	} else if eventFilteringOption == "whitelistedEvents" {
		delete(jsonConfig, "blacklistedEvents")
	} else if eventFilteringOption == "blacklistedEvents" {
		delete(jsonConfig, "whitelistedEvents")
	}
	return jsonConfig
}

func cleanupConsentManagementConfig(jsonConfig map[string]any) map[string]any {
	// Ensure each consent management object has "resolutionStrategy" defined. Otherwise, set to ""
	consentManagement, ok := jsonConfig["consentManagement"].(map[string]interface{})
	if ok {
		for _, platformValue := range consentManagement {
			platformArray, ok := platformValue.([]interface{})
			if !ok {
				continue
			}
			for _, item := range platformArray {
				consentManagementObjectMap, ok := item.(map[string]interface{})
				if !ok {
					continue
				}
				_, hasResolutionStrategy := consentManagementObjectMap["resolutionStrategy"]
				if !hasResolutionStrategy {
					consentManagementObjectMap["resolutionStrategy"] = ""
				}
			}
		}
	}
	return jsonConfig
}

// generateDestination generates a destination resource block from an API destination object and a terraform destination type and ConfigMeta.
func generateDestination(destination client.Destination, terraformType string, cm *configs.ConfigMeta) (block *hclwrite.Block, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic while generating destination block: %v", r)
		}
	}()

	resourceType := destinationType(terraformType)
	resourceName := destinationName(destination)
	block = hclwrite.NewBlock("resource", []string{resourceType, resourceName})

	body := block.Body()
	body.SetAttributeValue("name", cty.StringVal(destination.Name))

	if !cm.SkipConfig {
		destination = cleanupDestinationConfig(destination)

		configBlock, err := generateConfigBlock(destination.Config, cm)
		if err != nil {
			return nil, fmt.Errorf("could not generate config block for destination '%s': %w", destination.ID, err)
		}
		body.AppendBlock(configBlock)
	}

	return block, nil
}

func destinationType(terraformType string) string {
	return fmt.Sprintf("rudderstack_destination_%s", terraformType)
}

func destinationName(destination client.Destination) string {
	return fmt.Sprintf("dst_%s", destination.ID)
}

// configMeta finds a ConfigMeta of a specific api type. Returns the terraform type and the ConfigMeta if found.
// if not, it returns an empty string and nil.
func configMeta(entries map[string]configs.ConfigMeta, apiType string) (string, *configs.ConfigMeta) {
	for r, e := range entries {
		if e.APIType == apiType {
			return r, &e
		}
	}

	return "", nil
}

// generateConfigBlock generate a source or destination config block from an API config JSON
// and a corresponding ConfigMeta.
func generateConfigBlock(config json.RawMessage, cm *configs.ConfigMeta) (*hclwrite.Block, error) {
	// get state representation of config as map[string]interface{}
	state, err := cm.APIToState(string(config))
	if err != nil {
		return nil, fmt.Errorf("could not convert API config to terraform state: %w", err)
	}

	var stateMap map[string]interface{}
	if err := json.Unmarshal([]byte(state), &stateMap); err != nil {
		return nil, err
	}

	block, err := generateBlock("config", stateMap, cm.ConfigSchema)
	if err != nil {
		return nil, fmt.Errorf("could not generate config block: %w", err)
	}

	return block, nil
}

// generateBlock generate blocks with specified name and data which conform to the provided config schema.
// data should be unmarshalled from a state JSON object.
func generateBlock(name string, data map[string]interface{}, configSchema map[string]*schema.Schema) (*hclwrite.Block, error) {
	block := hclwrite.NewBlock(name, []string{})
	body := block.Body()

	// go does not guarantee the order of range in maps, we sort the keys so that the output is predictable
	var keys []string
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := data[k]
		if sch, ok := configSchema[k]; ok {
			// state objects are actually lists with a single object item
			if r, ok := sch.Elem.(*schema.Resource); ok && sch.Type == schema.TypeList && sch.ConfigMode != schema.SchemaConfigModeAttr {
				if l, ok := v.([]interface{}); ok && len(l) > 0 {
					if value, ok := l[0].(map[string]interface{}); ok {
						kBlock, err := generateBlock(k, value, r.Schema)
						if err != nil {
							return nil, err
						}
						body.AppendBlock(kBlock)
					}
				}
			} else {
				body.SetAttributeValue(k, ctyValue(v))
			}
		}
	}

	return block, nil
}

// ctyValue converts any value to a cty.Value which can be passed as values to HCL attributes
func ctyValue(x interface{}) cty.Value {
	switch v := x.(type) {
	case string:
		return cty.StringVal(v)

	case bool:
		return cty.BoolVal(v)

	case int:
	case int16:
	case int32:
	case int64:
		return cty.NumberIntVal(v)

	case float32:
	case float64:
		return cty.NumberFloatVal(v)

	case []interface{}:
		var values []cty.Value
		for _, i := range v {
			values = append(values, ctyValue(i))
		}
		if len(values) == 0 {
			return cty.ListValEmpty(cty.String)
		}

		// When elements are objects, a list attribute may be empty (cty.String placeholder
		// from the len==0 case above) in some elements but have a concrete type in others.
		// Collect concrete types first, then fix the placeholders so all elements have the same type.
		concreteAttrElemTypes := map[string]cty.Type{}
		for _, val := range values {
			if !val.Type().IsObjectType() {
				continue
			}
			for k, attrVal := range val.AsValueMap() {
				if attrVal.Type().IsListType() && !attrVal.Type().ElementType().Equals(cty.String) {
					concreteAttrElemTypes[k] = attrVal.Type().ElementType()
				}
			}
		}
		for i, val := range values {
			if !val.Type().IsObjectType() {
				continue
			}
			attrs := val.AsValueMap()
			for k, attrVal := range attrs {
				if elemType, ok := concreteAttrElemTypes[k]; ok &&
					attrVal.Type().IsListType() &&
					attrVal.Type().ElementType().Equals(cty.String) &&
					attrVal.LengthInt() == 0 {
					attrs[k] = cty.ListValEmpty(elemType)
					values[i] = cty.ObjectVal(attrs)
				}
			}
		}
		return cty.ListVal(values)
	case map[string]interface{}:
		values := map[string]cty.Value{}
		for k, i := range v {
			values[k] = ctyValue(i)
		}
		return cty.ObjectVal(values)
	}

	return cty.EmptyObjectVal
}

func generateConnection(connection client.Connection, source *sourceEntry, destination *destinationEntry) (*hclwrite.Block, error) {
	resourceType := "rudderstack_connection"
	resourceName := connectionName(connection)
	block := hclwrite.NewBlock("resource", []string{resourceType, resourceName})

	body := block.Body()

	body.SetAttributeRaw("source_id", hclwrite.Tokens{
		&hclwrite.Token{
			Type:  hclsyntax.TokenIdent,
			Bytes: []byte(fmt.Sprintf("%s.%s.id", sourceType(source.terraformType), sourceName(source.source))),
		},
	})

	body.SetAttributeRaw("destination_id", hclwrite.Tokens{
		&hclwrite.Token{
			Type:  hclsyntax.TokenIdent,
			Bytes: []byte(fmt.Sprintf("%s.%s.id", destinationType(destination.terraformType), destinationName(destination.destination))),
		},
	})

	return block, nil
}

func connectionName(connection client.Connection) string {
	return fmt.Sprintf("cnxn_%s", connection.ID)
}

// retlSourceTerraformType reports whether a RETL source can be emitted as a
// rudderstack_retl_source_* resource. Returns the terraform type, a reason
// string (populated on rejection so the caller can produce a useful warning),
// and an ok flag. Both `GenerateImportScript` and `GenerateTerraform` route
// every source through this single check so the two outputs can never
// disagree on which sources to include.
//
// A source is eligible iff:
//   - sourceType is `model` or `table` (S3 tables and audience/profiles types
//     are intentionally skipped — no matching resource exists in this PR),
//   - the API returned a config payload of the matching concrete type
//     (`RETLSQLModelConfig` or `RETLTableConfig`). RETLSource.UnmarshalJSON
//     leaves `Config` nil when the API returns null/empty config — those
//     sources can't be generated and must be filtered upstream of any HCL
//     emission, otherwise the import script would reference a non-existent
//     resource block.
func retlSourceTerraformType(s retl.RETLSource) (terraformType string, reason string, ok bool) {
	switch s.SourceType {
	case retl.ModelSourceType:
		if _, ok := s.Config.(retl.RETLSQLModelConfig); !ok {
			return "", fmt.Sprintf("sourceType 'model' but config is %T (expected RETLSQLModelConfig)", s.Config), false
		}
		return "rudderstack_retl_source_model", "", true
	case retl.TableSourceType:
		if s.SourceDefinitionName == "s3" {
			return "", "S3 table sources are not supported by this tool", false
		}
		if _, ok := s.Config.(retl.RETLTableConfig); !ok {
			return "", fmt.Sprintf("sourceType 'table' but config is %T (expected RETLTableConfig)", s.Config), false
		}
		return "rudderstack_retl_source_table", "", true
	default:
		return "", fmt.Sprintf("unsupported sourceType '%s'", s.SourceType), false
	}
}

// retlSourceName / retlConnectionName prefix the API ID with `retl_src_` /
// `retl_cnxn_` so the generated terraform identifiers are always valid even
// when the API ID starts with a digit (RudderStack IDs frequently do, and
// HCL identifiers must start with a letter or underscore).
func retlSourceName(s retl.RETLSource) string {
	return fmt.Sprintf("retl_src_%s", s.ID)
}

func retlConnectionName(c retl.RETLConnection) string {
	return fmt.Sprintf("retl_cnxn_%s", c.ID)
}

// generateRetlSource builds the resource block for a RETL source. The Config
// field is a sealed union (RETLSQLModelConfig / RETLTableConfig), so we type-
// switch to populate the right config block. Account references are emitted
// as literal strings until rudderstack_account_* resources ship.
func generateRetlSource(s retl.RETLSource, terraformType string) (block *hclwrite.Block, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic while generating RETL source block: %v", r)
		}
	}()

	block = hclwrite.NewBlock("resource", []string{terraformType, retlSourceName(s)})
	body := block.Body()
	body.SetAttributeValue("name", cty.StringVal(s.Name))
	body.SetAttributeValue("source_definition_name", cty.StringVal(s.SourceDefinitionName))
	body.SetAttributeValue("account_id", cty.StringVal(s.AccountID))
	body.SetAttributeValue("enabled", cty.BoolVal(s.IsEnabled))

	configBlock := hclwrite.NewBlock("config", nil)
	cfgBody := configBlock.Body()
	switch cfg := s.Config.(type) {
	case nil:
		// retl.RETLSource.UnmarshalJSON leaves Config nil when the API returns
		// a null/empty config payload. We can't generate a valid HCL block
		// without it — bail out so the source is logged-and-skipped upstream.
		return nil, fmt.Errorf("RETL source has no config (API returned null) — cannot generate")
	case retl.RETLSQLModelConfig:
		cfgBody.SetAttributeValue("primary_key", cty.StringVal(cfg.PrimaryKey))
		cfgBody.SetAttributeValue("sql", cty.StringVal(cfg.Sql))
		if cfg.Description != "" {
			cfgBody.SetAttributeValue("description", cty.StringVal(cfg.Description))
		}
	case retl.RETLTableConfig:
		cfgBody.SetAttributeValue("primary_key", cty.StringVal(cfg.PrimaryKey))
		cfgBody.SetAttributeValue("schema", cty.StringVal(cfg.Schema))
		cfgBody.SetAttributeValue("table", cty.StringVal(cfg.Table))
	default:
		return nil, fmt.Errorf("unexpected RETL source config type %T", s.Config)
	}
	body.AppendBlock(configBlock)
	return block, nil
}

// generateRetlConnection builds the resource block for a RETL connection. The
// connection's source_id and destination_id are emitted as terraform resource
// references (so terraform can manage the dependency graph), and the rest of
// the flat API response is split back into the nested HCL blocks the resource
// schema expects.
func generateRetlConnection(c retl.RETLConnection, src *retlSourceEntry, dst *destinationEntry) (block *hclwrite.Block, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic while generating RETL connection block: %v", r)
		}
	}()

	block = hclwrite.NewBlock("resource", []string{"rudderstack_retl_connection", retlConnectionName(c)})
	body := block.Body()

	body.SetAttributeRaw("source_id", hclwrite.Tokens{
		&hclwrite.Token{
			Type:  hclsyntax.TokenIdent,
			Bytes: []byte(fmt.Sprintf("%s.%s.id", src.terraformType, retlSourceName(src.source))),
		},
	})
	body.SetAttributeRaw("destination_id", hclwrite.Tokens{
		&hclwrite.Token{
			Type:  hclsyntax.TokenIdent,
			Bytes: []byte(fmt.Sprintf("%s.%s.id", destinationType(dst.terraformType), destinationName(dst.destination))),
		},
	})

	body.SetAttributeValue("enabled", cty.BoolVal(c.Enabled))
	body.SetAttributeValue("sync_behaviour", cty.StringVal(string(c.SyncBehaviour)))

	body.AppendBlock(retlScheduleBlock(c.Schedule))

	if ss := retlSyncSettingsBlock(c.SyncSettings); ss != nil {
		body.AppendBlock(ss)
	}

	for _, id := range c.Identifiers {
		body.AppendBlock(retlMappingBlock("identifiers", id))
	}
	for _, m := range c.Mappings {
		body.AppendBlock(retlMappingBlock("mappings", m))
	}

	if c.Event != nil {
		body.AppendBlock(retlEventBlock(c.Event))
	}

	for _, k := range c.Constants {
		cb := hclwrite.NewBlock("constants", nil)
		cb.Body().SetAttributeValue("key", cty.StringVal(k.Key))
		cb.Body().SetAttributeValue("value", cty.StringVal(k.Value))
		body.AppendBlock(cb)
	}

	if c.CursorColumn != "" {
		body.SetAttributeValue("cursor_column", cty.StringVal(c.CursorColumn))
	}
	if c.Object != "" {
		body.SetAttributeValue("object", cty.StringVal(c.Object))
	}
	// The caller has already filtered out destination-specific flows that
	// aren't Customer.io Audience and pre-validated the typed block, so any
	// non-empty destinationConfig here belongs to a customerio_audience
	// destination and decodes cleanly. The error path is unreachable in
	// normal flow; treat it as fail-fast so a future refactor that drops
	// the pre-check can't silently emit unimportable HCL.
	if len(c.DestinationConfig) > 0 {
		b, err := customerIOAudienceConfigBlock(c.DestinationConfig)
		if err != nil {
			return nil, fmt.Errorf("decode customerio_audience destinationConfig: %w", err)
		}
		body.AppendBlock(b)
	}

	return block, nil
}

func retlScheduleBlock(s retl.Schedule) *hclwrite.Block {
	b := hclwrite.NewBlock("schedule", nil)
	body := b.Body()
	body.SetAttributeValue("type", cty.StringVal(string(s.Type)))
	if s.EveryMinutes != nil {
		body.SetAttributeValue("every_minutes", cty.NumberIntVal(int64(*s.EveryMinutes)))
	}
	if s.CronExpression != nil {
		body.SetAttributeValue("cron_expression", cty.StringVal(*s.CronExpression))
	}
	return b
}

func retlSyncSettingsBlock(ss *retl.SyncSettings) *hclwrite.Block {
	if ss == nil || (ss.SyncLogsConfig == nil && ss.FailedKeysConfig == nil) {
		return nil
	}
	b := hclwrite.NewBlock("sync_settings", nil)
	body := b.Body()
	if ss.SyncLogsConfig != nil {
		logsBlock := hclwrite.NewBlock("sync_logs_config", nil)
		logsBody := logsBlock.Body()
		if ss.SyncLogsConfig.Enabled != nil {
			logsBody.SetAttributeValue("enabled", cty.BoolVal(*ss.SyncLogsConfig.Enabled))
		}
		if ss.SyncLogsConfig.LogRetentionInDays != nil {
			logsBody.SetAttributeValue("log_retention_in_days", cty.NumberIntVal(int64(*ss.SyncLogsConfig.LogRetentionInDays)))
		}
		if ss.SyncLogsConfig.SnapshotsToRetain != nil {
			logsBody.SetAttributeValue("snapshots_to_retain", cty.NumberIntVal(int64(*ss.SyncLogsConfig.SnapshotsToRetain)))
		}
		body.AppendBlock(logsBlock)
	}
	if ss.FailedKeysConfig != nil {
		fkBlock := hclwrite.NewBlock("failed_keys_config", nil)
		if ss.FailedKeysConfig.EnableFailedKeysRetry != nil {
			fkBlock.Body().SetAttributeValue("enable_failed_keys_retry", cty.BoolVal(*ss.FailedKeysConfig.EnableFailedKeysRetry))
		}
		body.AppendBlock(fkBlock)
	}
	return b
}

func retlMappingBlock(name string, m retl.Mapping) *hclwrite.Block {
	b := hclwrite.NewBlock(name, nil)
	b.Body().SetAttributeValue("from", cty.StringVal(m.From))
	b.Body().SetAttributeValue("to", cty.StringVal(m.To))
	return b
}

func retlEventBlock(e *retl.Event) *hclwrite.Block {
	b := hclwrite.NewBlock("event", nil)
	body := b.Body()
	body.SetAttributeValue("type", cty.StringVal(string(e.Type)))
	if e.Name != "" {
		body.SetAttributeValue("name", cty.StringVal(e.Name))
	}
	if e.NameColumn != "" {
		body.SetAttributeValue("name_column", cty.StringVal(e.NameColumn))
	}
	return b
}

// customerIOAudienceConfigBlock builds a `customerio_audience_config` block
// from the connection's destinationConfig JSON. Returns an error if the JSON
// is missing/invalid or audienceId is absent or not a number — the caller
// logs and skips the block in that case.
func customerIOAudienceConfigBlock(raw json.RawMessage) (*hclwrite.Block, error) {
	var parsed map[string]interface{}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return nil, fmt.Errorf("destinationConfig is not valid JSON: %w", err)
	}
	v, ok := parsed["audienceId"]
	if !ok {
		return nil, fmt.Errorf("customerio_audience destinationConfig missing audienceId")
	}
	n, ok := v.(float64) // json.Unmarshal decodes numbers as float64
	if !ok {
		return nil, fmt.Errorf("customerio_audience audienceId is %T, expected number", v)
	}
	if math.IsNaN(n) || math.IsInf(n, 0) || math.Trunc(n) != n {
		return nil, fmt.Errorf("customerio_audience audienceId %v is not an integer", n)
	}
	b := hclwrite.NewBlock("customerio_audience_config", nil)
	b.Body().SetAttributeValue("audience_id", cty.NumberIntVal(int64(n)))
	return b, nil
}
